[Variables]
Main_FG =F5604A
Secondary_FG =FFE2A6
Main_BG =131C39
Sidebar_And_Player_BG =2E2837
Cover_Overlay_And_Shadow =000000
Indicator_FG_And_Button_BG =DD3741
Pressing_FG = FF5C86
Slider_BG =131C39
Sidebar_Indicator_And_Hover_Button_BG =00BF76
Scrollbar_FG_And_Selected_Row_BG =1F1B29
Pressing_Button_FG =DEDEDE
Pressing_Button_BG =383145
Selected_Button =00BF76
Miscellaneous_BG =131C39
Miscellaneous_Hover_BG =131C39
Preserve_1 =B02525
